## 02: Functions and Control Flow
### Section 4.1-6.1

#### List Comprehension

In [4]:
L1=[1,2,3,4,5,6,7,8,9]
L2=[x**2 for x in L1] # we can create a new list from an existing one
print(L1)
print(L2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [5]:
# We can do the same like this
[x**2 for x in range(1,10)]

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [6]:
# strings are also iterable
for c in "dog":
    print(c)

d
o
g


In [7]:
# and do alike for dictionaries
d={"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8,"i":9}
[d[c] for c in "cicada"]

[3, 9, 3, 1, 4, 1]

In [8]:
# add a condition for inclusion
L1=[1, 2, 3, 4,5,6,7,8,9,10,11,12]
print(L1)
L2=[x for x in L1 if x%2==0] # % is used for remainer (8%2=0)
print(L2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[2, 4, 6, 8, 10, 12]


In [9]:
# we can also loop inside a loop
L=[]
for i in range(1,6):
    for j in range(i,6):
        L.append((i,j))
print(L)

# the compact way
L1=[(i,j) for i in range(1,6) for j in range(i,6)]
print(L1)

[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 2), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5), (4, 4), (4, 5), (5, 5)]
[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (2, 2), (2, 3), (2, 4), (2, 5), (3, 3), (3, 4), (3, 5), (4, 4), (4, 5), (5, 5)]


#### Functions

In [10]:
import numpy as np  
# def function(parameters):
def normalization(x,L):     
    # the body of the function is indented.
    # "local" (function parts) variables are created as needed
    mean = np.mean(L)
    sd = np.std(L, ddof=1) #for sample, 0 for population
    z = (x-mean)/sd
    # one of the local variables (z) is returned (optional), print statement for debugging
    print("z:", z, "~ N(", mean, ",", sd, ")") 
    return z

df = [1,2,3,4,5,6,7]
normalization(4,df)

z: 0.0 ~ N( 4.0 , 2.160246899469287 )


np.float64(0.0)

In [11]:
# Built in functions have optional arguments as well
print('my', 'life', 'sux', end='?', sep='__')

my__life__sux?

In [12]:
def myfunction(u):
    if u<=.5: # if u<=0.7 return 1, else return 0
        return(1)
    return(0)

# this does the same thing
def myfunction(u):
    if u<=.5:
        return(1)
    else:
        return(0)
    
import numpy as np
for i in range(10):
    u=np.random.uniform() # samples uniformly from 0 to 1
    x=myfunction(u) 
    print(x)

0
0
0
0
0
0
0
1
0
0


In [13]:
# we can expand with else-if or elif
# x     0       1       2       3
# p(x)  0.4     0.2     0.15    0.25
def myfunction(u):
    if 0 <= u and u <=.4:
        return(0)
    elif .4<u and u<=.6:
        return(1)
    elif .6<u and u<=.75:
        return(2)
    else:
        return(3)
import numpy as np
L=[]
for i in range(20):
    L.append(myfunction(np.random.uniform()))
print(L)


[2, 0, 0, 0, 3, 0, 3, 0, 1, 0, 1, 0, 0, 2, 1, 1, 0, 0, 1, 0]


In [14]:
# break exits the CURRENT loop
for i in range(10):
    if i>5:
        break
    print(i)
print("done")

0
1
2
3
4
5
done


In [15]:
# continue ignores the rest of the loop and moves to the next iteration
for i in range(5):
    print(i)
    if i==3:
        print("continue encountered")
        continue # don't execute any more code inside the loop
        print("get rekt")
    print(i)

0
0
1
1
2
2
3
continue encountered
4
4


In [16]:
# pass is used as a dummy in place of uncompleted stuff
for i in range(7):
    if i>3:
        pass
    print(i)

0
1
2
3
4
5
6


In [17]:
# runs while a condition is true
i=1
while True: # using True makes code run until a break is encountered
    i+=1 # i=i+1 
    print(i)
    if i>5:
        break
print("done")

2
3
4
5
6
done


In [18]:
# python doesn't have switch-case looping, but we can do it with a dictionary
def f0():
    return("8AM")
def f1():
    return("8AM")
def f2():
    return("10AM")
def f3():
    return("9AM")
def f4():
    return("8AM")

arrival_time={"Mon":f0,"Tue":f1,"Wed":f2,"Thu":f3,"Fri":f4}
arrival_time["Tue"]()

'8AM'

In [19]:
# Functions can take arguments in any order, as long as it's specified
import cmath as c
def quadratic_formula(A,B,C):
    d=B*B-4*A*C
    rtd=c.sqrt(d)
    root1=(-B-rtd)/(2*A)
    root2=(-B+rtd)/(2*A)
    return((root1,root2))
print(quadratic_formula(1,5,6))
print(quadratic_formula(6,5,1))
print(quadratic_formula(C=6,B=5,A=1)) # assignment matters

((-3+0j), (-2+0j))
((-0.5+0j), (-0.3333333333333333+0j))
((-3+0j), (-2+0j))


In [20]:
# We can also set default values
def quadratic_formula(A,C,B=0): # arguments without default values must come first, we can force positional arguemnts like (*,a,b,c)
    d=B*B-4*A*C
    rtd=c.sqrt(d)
    root1=(-B-rtd)/(2*A)
    root2=(-B+rtd)/(2*A)
    return((root1,root2))
print(quadratic_formula(A=1, C=-9))

((-3+0j), (3+0j))


In [21]:
# Variable number of arguments used by asterisk first
def concat_strings(*v,sep=",",end=""):
    print('Values (v) dtype:', type(v)) 
    print(v)
    print(len(v))
    for i in range(len(v)):
        print(v[i])
    print(sep)
    print(end)

concat_strings("dog","cat","bird",sep="DAN",end="Q")

Values (v) dtype: <class 'tuple'>
('dog', 'cat', 'bird')
3
dog
cat
bird
DAN
Q


In [22]:
# Test implementation
def concat_strings(*values,sep=",",end=""):
    mystring=""
    for v in values[:-1]:
        mystring+=v+sep
    mystring+=values[-1]+end
    return(mystring)  

print(concat_strings("my","dog","ate","my","homework"))
print(concat_strings("my","dog","ate","my",sep="_"))
print(concat_strings("my","dog","ate",sep=" "))
print(concat_strings("my","dog",sep="_",end="++++"))
print(concat_strings("my",sep=","))

my,dog,ate,my,homework
my_dog_ate_my
my dog ate
my_dog++++
my


In [23]:
# Force arguments to be named
import cmath as c
def quad(*,A,B,C):
    d=B*B-4*A*C
    rtd=c.sqrt(d)
    root1=(-B-rtd)/(2*A)
    root2=(-B+rtd)/(2*A)
    return((root1,root2))

quad(A=1,B=0.25,C=0.5)

((-0.125-0.6959705453537527j), (-0.125+0.6959705453537527j))

In [24]:
# Required arguments and any number of optional arguments
def h(p1,p2,*myextra):
    print("first required positional argument is ", p1)
    print("second required positional argument is ", p2)
    print(type(myextra))
    if len(myextra)>0:
        print("you supplied ", len(myextra), " optional arguments")
        ctr=0
        for e in myextra:
            print("   optional argument ", ctr, " is ", e)
            ctr+=1
    else:
        print("you did not supply any optional arguments")
    return   

h(9,3,4,5,6,7,10)

first required positional argument is  9
second required positional argument is  3
<class 'tuple'>
you supplied  5  optional arguments
   optional argument  0  is  4
   optional argument  1  is  5
   optional argument  2  is  6
   optional argument  3  is  7
   optional argument  4  is  10


In [25]:
# artibrary number of arguments
def f(**x):
    print(type(x))
    print(len(x))
    for k in x.keys():
        print("key = ", k, "  value = ", x[k])

f(i=7,j=9,c=11)

<class 'dict'>
3
key =  i   value =  7
key =  j   value =  9
key =  c   value =  11


In [26]:
# Arbitrary number of both positional and keyword arguments
def g(*pargs,**kwargs): #Position (*) tuple, Keyword (**) dictionary
    # here pargs is a tuple kwargs is a dictionary
    ctr=0
    print(pargs)
    for p in pargs:
        print("positional argument ", ctr, " = ", p)
        ctr+=1
    ctr=0
    print(kwargs)
    for k in kwargs.keys():
        print("keyword argument = ", ctr," key = ", k, "  value = ", kwargs[k])
        ctr+=1

g(6,7,c="47",a=56,b=92)
print('\n')
g(c="47",a=56,b=92)
print('\n')
g(6,7,8,9) # order must still be correct: pards, kwargs NOT kwargs, pargs

(6, 7)
positional argument  0  =  6
positional argument  1  =  7
{'c': '47', 'a': 56, 'b': 92}
keyword argument =  0  key =  c   value =  47
keyword argument =  1  key =  a   value =  56
keyword argument =  2  key =  b   value =  92


()
{'c': '47', 'a': 56, 'b': 92}
keyword argument =  0  key =  c   value =  47
keyword argument =  1  key =  a   value =  56
keyword argument =  2  key =  b   value =  92


(6, 7, 8, 9)
positional argument  0  =  6
positional argument  1  =  7
positional argument  2  =  8
positional argument  3  =  9
{}


In [27]:
# combining all three
def function(x, y=0, *pargs,**kwargs):
    print("required argument r1 = ", x)
    print("required argument r2 = ", y)
    i=0
    for p in pargs:
        print("positional argument ", i," = ", p)
        i+=1
    n=0
    for k in kwargs.keys():
        print("keyword argument = ", n, " key = ", k, "  value = ", kwargs[k])
        n+=1

#### Map and Lambda

In [28]:
# map functions are like R's sapply() and lapply()
L=[0,1,2,3,4] 
def squareit(x):
    return(x**2)

M=list(map(squareit,L)) # applies function to list
print(type(M))
print(M)


<class 'list'>
[0, 1, 4, 9, 16]


In [29]:
# lambda is used for nameless functions
f=lambda x:x*x 
print(f(10))
(lambda x:x*x)(10) # we don;t need to name the function either

100


100

In [30]:
# combining lambdas and maps
L=[(1,2),(3,4),(5,6)]
M=map(lambda p: (p[0]+p[1],p[0]*p[1]),L) # using tuples, (1+2,1*2),(3+4,3*4)
for m in M:
    print(m)

(3, 2)
(7, 12)
(11, 30)


#### Sorting

In [31]:
# objects must be comparable for sorting, ie no strings and ints in the same list
A=[1,7,2,6,5,4,3]
A.sort()
print(A)

B=["abacus","about","aaa","ancillary","a","abracadabra","above","aaaa"]
B.sort()
print(B)

B.sort(reverse=True) #reverse order
print(B)

[1, 2, 3, 4, 5, 6, 7]
['a', 'aaa', 'aaaa', 'abacus', 'about', 'above', 'abracadabra', 'ancillary']
['ancillary', 'abracadabra', 'above', 'about', 'abacus', 'aaaa', 'aaa', 'a']


In [32]:
L=[1,7,2,6,5,4,3]
L2=L.sort() # no value
L3=L.copy() # sorted L
print(L) #L will also be sorted
print(L2)
print(L3)


[1, 2, 3, 4, 5, 6, 7]
None
[1, 2, 3, 4, 5, 6, 7]


In [33]:
# sorted can be used instead to denote L2 as sorted L1
L1=[1,7,2,6,5,4,3]
L2=sorted(L1)
L3=sorted(L1, reverse=True)
print(L1)
print(L2)
print(L3)


[1, 7, 2, 6, 5, 4, 3]
[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 1]


In [34]:
L=[(19,[3,5],27),(3,[81,1],5),(9,[81,2],97),(2,[7,0],1)]
# x[1] takes the second element (the list) and then x[1][1] takes the second element 
# if a tie exists, pass x[1][1] and sort by x[0] instead
sorted(L,key=lambda x:(x[1][1],x[0])) 

[(2, [7, 0], 1), (3, [81, 1], 5), (9, [81, 2], 97), (19, [3, 5], 27)]

In [35]:
d={10:'dog',7:'dog',12:'bird', 13:'dog'}

# Sorting dictionaries 
print(sorted(d)) # only captures keys
print(sorted(d.items())) # sort by key (nums)
print(sorted(d.items(),key=lambda x:x[1])) # sort by value (animals)
print(sorted(d.items(),key=lambda x:(x[1],x[0]))) # sort by values, break ties by keys

[7, 10, 12, 13]
[(7, 'dog'), (10, 'dog'), (12, 'bird'), (13, 'dog')]
[(12, 'bird'), (10, 'dog'), (7, 'dog'), (13, 'dog')]
[(12, 'bird'), (7, 'dog'), (10, 'dog'), (13, 'dog')]


In [36]:
# zip can be useful to generate tuples from lists where i=j
L1=[1,2,3,4,5]
L2=[6,7,8,9,10]
z=zip(L1,L2)
for x in z:
    print(x)

(1, 6)
(2, 7)
(3, 8)
(4, 9)
(5, 10)


In [37]:
L=[78,21,32,1,18,29,65,42,38]
for e in enumerate(L): # enumarate assigns indexes: (0,78), (1,21),...
    if e[1]==18: # e[1] is the value
        print(e[0]) # e[0] is the index

4


#### Generators

In [38]:
# Generators generate values and the state is saved
# Yield() instantiates a generator
def NaturalNumberSquares():
    n=1
    yield(n)
    while True:
        n+=1
        yield(n**2)  

#we can get values via next()
g=NaturalNumberSquares()
print(next(g), "\t", next(g), "\t", next(g), "\t", next(g), "\t", next(g))

# generators are independent
g2=NaturalNumberSquares()
print(next(g2), "\t", next(g2), "\t", next(g2), "\t", next(g2), "\t", next(g2))
print(next(g), "\t", next(g), "\t", next(g), "\t", next(g), "\t", next(g))



1 	 4 	 9 	 16 	 25
1 	 4 	 9 	 16 	 25
36 	 49 	 64 	 81 	 100


In [39]:
# to add a breakpoint to a generator
def NaturalNumberSquares():
    n=1
    yield(n)
    while True:
        n+=1
        yield(n**2)
        if n>5:
            break

g=NaturalNumberSquares()
for i in range(10):
    try:
        print(i,next(g))
    except StopIteration:
        print("no value generated")
print("done")

0 1
1 4
2 9
3 16
4 25
5 36
no value generated
no value generated
no value generated
no value generated
done


In [40]:
# Fibbonaaci Generator
def fibonacci(n):
    """
    Generate the first n Fibonacci numbers along with their indices.
    """
    a, b = 0, 1              # Initialize the first two Fibonacci numbers: F(0)=0, F(1)=1
    for i in range(n):       # Loop n times to generate n Fibonacci numbers
        yield i, a           # Yield (index, Fibonacci number) as a tuple
        a, b = b, a + b      # Update: next Fibonacci number = sum of previous two

# Example usage:
for idx, val in fibonacci(10):      # Generate first 10 Fibonacci numbers
    print(idx, val)                 # Print index and Fibonacci number

0 0
1 1
2 1
3 2
4 3
5 5
6 8
7 13
8 21
9 34


In [41]:
# alternative to set up generator
gsquares = (x*x for x in range(10))
print(type(gsquares))

for i in range(6):
    print(next(gsquares))

<class 'generator'>
0
1
4
9
16
25


#### numpy

In [42]:
# Always convert to array so numpy doesnt freak out
import numpy as np

x=[1.,2.,3.,4.,5.]
y=[5.,6.,7.,8.,9.]
xv=np.array(x) # construct an array
yv=np.array(y)
print(type(xv), 'with dimensions:', xv.shape) #gives dimensions
print('x as a vector:',xv)
print('xvec+yvec:', xv+yv)
print('3xvec:', 3.*xv)

<class 'numpy.ndarray'> with dimensions: (5,)
x as a vector: [1. 2. 3. 4. 5.]
xvec+yvec: [ 6.  8. 10. 12. 14.]
3xvec: [ 3.  6.  9. 12. 15.]


In [43]:
# multidimensional arrays
A=np.array([[1,2,3], #2x3
            [4,5,6]])
B=np.array([[7,8], #3x2
            [9,10],
            [11,12]])
print(A@B) #2x2, @ for mat mult

[[ 58  64]
 [139 154]]


In [44]:
# slicing works the same way
A=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(A)
print(A[2:4,1:3]) #3rd matrix, second and third element
print(A[2:4,:]) #third matrix
print(A[:,1:3]) #2nd and 3rd element of each list

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[12 13]]
[[11 12 13 14 15]]
[[ 2  3]
 [ 7  8]
 [12 13]]


In [45]:
# need to specify object datatype if working with mixed types
d={"a":1,"b":2}
L=[1,2,3]
t=(1,2)
st="dog"
x=np.array([[d,L],[t,st]],dtype="object")
print(x)
print(x.dtype)

[[{'a': 1, 'b': 2} list([1, 2, 3])]
 [(1, 2) 'dog']]
object


In [46]:
# convert datatype with astype()
x=np.array([["3.14159","2.71828"],["98.6","100.3"]])
x=x.astype("float")
print(x)

[[  3.14159   2.71828]
 [ 98.6     100.3    ]]


In [47]:
# numpy float and python float are not the same
import numpy as np
x=[1.,2.,3.]
xv=np.array(x)
u=xv[0]
print(type(u))
v=float(u)
print(type(v))

<class 'numpy.float64'>
<class 'float'>


In [48]:
# transpose operator
A=np.array([[1,2,3,4],[5,6,7,8]])
print(A)
print("\n")
print(A.T)

[[1 2 3 4]
 [5 6 7 8]]


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [49]:
# similarily we can do dot products two different ways
x=np.array([1,2,3,4,5])
y=np.array([1,2,3,4,5])
print(x.dot(y))
print((x*y).sum()) # equivalent way

55
55


In [50]:
# norms are used to find size of an array
x=np.array([3,4,5])
print('Euclidean Norm:', np.linalg.norm(x,2)) # sqrt of (3^2 + 4^2 + 5^2)
print('L1 norm:', np.linalg.norm(x,1)) # 3+4+5
print('argmax norm:', np.linalg.norm(x,np.inf)) # np.inf=max(3,4,5)

# various useful operations
print('The sum is:', x.sum(), '\nthe lowest and highest are:', x.min(),'and',x.max(), '\nwith mean and sd', x.mean(),'and', x.std())

Euclidean Norm: 7.0710678118654755
L1 norm: 12.0
argmax norm: 5.0
The sum is: 12 
the lowest and highest are: 3 and 5 
with mean and sd 4.0 and 0.816496580927726


In [51]:
# creating arrays of 1, 0, and spaced
array1 = np.ones((3,2))
array0=np.zeros((2,3))
array=np.linspace(1,11,6)
print(array)
print(array0)
print(array1)

[ 1.  3.  5.  7.  9. 11.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [52]:
# diagonal = diag, identity=eye
identity = np.eye(3,3)
diagonal=np.diag([1,2,3])
print(identity, '\n', diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [53]:
# functions can also operate component wise
x=[1,4,9,16,25]
y=np.sqrt(x)
print(y)


[1. 2. 3. 4. 5.]


In [54]:
# load data with numpy
data='''
name,job,"age","height"
fred,chef,71,61.5
sally,dietician,35,58.2
leslie,realtor,45,62.0
jim,waiter,29,58.1
'''
with open("datafile.csv","w") as fout:
    fout.write(data)

A=np.loadtxt("datafile.csv",delimiter=",",dtype="str")
print(A)

[['name' 'job' '"age"' '"height"']
 ['fred' 'chef' '71' '61.5']
 ['sally' 'dietician' '35' '58.2']
 ['leslie' 'realtor' '45' '62.0']
 ['jim' 'waiter' '29' '58.1']]


/var/folders/38/22n3rn6s7gjdhyf__np8757r0000gn/T/ipykernel_40116/1815848868.py:12: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  A=np.loadtxt("datafile.csv",delimiter=",",dtype="str")


In [55]:
# reshaping data
x=np.array([1,2,3,4,5,6])
print(x.reshape(2,3))
print('\n')
print(x.reshape(6)) # if column isn't given, only row prints
print('\n')
print(x.reshape(6,1))
print('\n')

[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6]


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]




In [56]:
# flattening 'flattens' the data
x=np.array([[1],[2],[3],[4],[5]])
print(x)
print('\n')
x=x.flatten()
print(x)

[[1]
 [2]
 [3]
 [4]
 [5]]


[1 2 3 4 5]
